import { Navbar } from "../components/Navbar";
import Head from "next/head";
import { useHelloRoute } from "../hooks/useHelloRoute";
import styles from "@/styles/about.module.css";

const calculateBackgroundColor = (index: number) => {
  /* more gray the higher the index */
  const gray = 255 - index * 60;
  return `rgb(${gray}, ${gray}, ${gray})`;
};

export default function About() {
  const { data, error } = useHelloRoute();
  const cards = data?.cards || [];
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar activePage="about" />

        <h1>About us</h1>
        {data ? (
          <div className={styles.row}>
            {cards.map((card, index) => (
              <div
                key={index}
                className={styles.card}
                style={{
                  backgroundColor: calculateBackgroundColor(
                    cards.length - index
                  ),
                }}
              >
                <h3>{card.title} &rarr;</h3>
                <p>{card.description}</p>
              </div>
            ))}
          </div>
        ) : (
          <span>Loading...</span>
        )}
      </main>
    </>
  );
}
