import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from '@/styles/Home.module.css'
import { Navbar } from "../components/Navbar";

import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [count, setCount] = useState(0);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar activePage="home" />
        <div>
          <h1>Home</h1>
          <button onClick={() => setCount(count + 1)}>Click me</button>
          <p>Count: {count}</p>
        </div>
      </main>
    </>
  );
}


