import Head from "next/head";
import styles from '@/styles/watchlist.module.css'
import { Navbar } from "../components/Navbar";

export default function Watchlist() {
  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar activePage="watchlist" />
        <div className={styles.body}>
          <h1 className={styles.title}>Stocks of interest</h1>
          <form className={styles.form}>
            <label className={styles.form_group}>Add stock to watchlist</label>
            <br/>
            <input 
              className={styles.form_group}
              name="symbol"
              placeholder="Enter a stock symbol"
            />
            <button className={styles.form_group} type='submit'>Submit</button>
          </form>
          <div className={styles.container}>
            Watchlist goes here
          </div>
        </div>
      </main>
    </>
  );
}